version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo npm ci
      - npm ci
      - ls
      - ls -la
artifacts:
  files:
    - node_modules/
    - public/
    - views/
    - index.js
  exclude-paths:
    - ".git"
