version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo npm ci
      - npm ci
      - ls
      - ls -la
artifacts:
  files:
    - /**/*
  exclude-paths:
    - ".git"
